import { Search } from "./icons";

/*
 * Figma 🧩 Components 페이지의 컴포넌트들을 그대로 옮긴 것.
 * 이름은 Figma 쪽 이름을 따랐다 (Card/UnderText, Tag/Color, Form/Button3, Search/GB).
 */

/** Card/UnderText — 이미지 자리 + 아래 캡션 */
export function CardUnderText({
  caption,
  overlay,
}: {
  caption: string;
  overlay?: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-4">
      {/* 412x564 (Figma). 실제 이미지가 들어오면 이 블록을 교체하면 된다. */}
      <div className="relative aspect-[412/564] w-full rounded-md bg-placeholder">
        {overlay}
      </div>
      <p className="text-center text-[15px] font-medium text-fg">{caption}</p>
    </div>
  );
}

/** Tag/Color — 색 스와치 + hex 라벨 */
export function TagColor({ hex }: { hex: string }) {
  return (
    <div className="flex items-center gap-1.5 rounded-lg bg-surface px-3 py-1.5">
      <span
        className="size-2.5 shrink-0 rounded-full"
        style={{ backgroundColor: hex }}
      />
      <span className="text-xs font-semibold text-fg">{hex}</span>
    </div>
  );
}

/** Form/Button3 — 설명 + 칩 3개 */
export function FormButton3() {
  const chips = [
    { label: "First", filled: true },
    { label: "Second", filled: true },
    { label: "Third", filled: false },
  ];
  return (
    <div className="flex flex-col gap-3 rounded-md bg-surface p-4">
      <div className="flex flex-col gap-1">
        <p className="text-[13px] font-bold text-fg">In context</p>
        <p className="text-[11px] leading-[1.4] font-normal text-fg-muted">
          Content detected as likely generated by AI
        </p>
      </div>
      <div className="flex flex-wrap gap-1">
        {chips.map((c) => (
          <span
            key={c.label}
            className={`flex h-6 items-center rounded-md px-2.5 text-[10px] font-semibold ${
              c.filled
                ? "bg-fg text-on-action"
                : "border border-fg text-fg"
            }`}
          >
            {c.label}
          </span>
        ))}
      </div>
    </div>
  );
}

/** Search/GB — 다크 패널 위에 얹히는 반투명 검색 pill */
export function SearchGB({ placeholder }: { placeholder: string }) {
  return (
    <div className="flex h-14 w-full max-w-[480px] items-center gap-3 rounded-[28px] border border-white/100 bg-white/15 px-6 backdrop-blur-sm">
      <Search className="size-[18px] shrink-0 text-white" />
      <span className="text-md font-medium text-white">{placeholder}</span>
    </div>
  );
}
