/**
 * Figma `Form/Button3` — 설명 + 칩 3개가 든 작은 오버레이 카드.
 * Figma 이름이 버튼처럼 보이지만 실제로는 카드라서 이름을 바꿔 뒀다.
 */

const chips = [
  { label: "First", filled: true },
  { label: "Second", filled: true },
  { label: "Third", filled: false },
];

export function ContextCard({
  title = "In context",
  description = "Content detected as likely generated by AI",
}: {
  title?: string;
  description?: string;
}) {
  return (
    <div className="flex flex-col gap-3 rounded-md bg-surface p-4">
      <div className="flex flex-col gap-1">
        <p className="text-[13px] font-bold text-fg">{title}</p>
        <p className="text-[11px] leading-[1.4] font-normal text-fg-muted">
          {description}
        </p>
      </div>
      <div className="flex flex-wrap gap-1">
        {chips.map((c) => (
          <span
            key={c.label}
            className={`flex h-6 items-center rounded-md px-2.5 text-[10px] font-semibold ${
              c.filled ? "bg-fg text-on-action" : "border border-fg text-fg"
            }`}
          >
            {c.label}
          </span>
        ))}
      </div>
    </div>
  );
}
